import pandas as pd
import joblib
import traceback
from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime

app = Flask(__name__)
CORS(app)

model_pipeline = None

def load_model():
    global model_pipeline
    try:
        model_filename = 'final_crop_model.joblib'
        model_pipeline = joblib.load(model_filename)
        print(f"Model '{model_filename}' loaded successfully.")
    except FileNotFoundError:
        print(f"Error: Model file '{model_filename}' not found.")
        model_pipeline = None
    except Exception as e:
        print(f"An error occurred while loading the model: {e}")
        model_pipeline = None

load_model()

def format_prediction_to_detailed_json(raw_predictions, input_data):
    targets = ['total_duration_estimate'] + \
              [f'{stage}_{metric}' for stage in ['sw', 'sd_e', 'tilrr', 'stel', 'btng', 'hdng', 'flwr', 'grnm', 'grnd', 'rpng', 'hrvst'] for metric in ['tmin', 'tmax', 'rh', 'rain', 'wind']] + \
              [f'{stage}_stage_dur' for stage in ['sw', 'sd_e', 'tilrr', 'stel', 'btng', 'hdng', 'flwr', 'grnm', 'grnd', 'rpng', 'hrvst']]
    
    results_df = pd.DataFrame(raw_predictions, columns=targets)
    
    stage_map = {
        "sw": {"name": "Sowing & Germination", "importance_weight": 1.4},
        "sd_e": {"name": "Seedling / Emergence", "importance_weight": 1.2},
        "tilrr": {"name": "Tillering", "importance_weight": 1.6},
        "stel": {"name": "Stem Elongation", "importance_weight": 1.4},
        "btng": {"name": "Booting", "importance_weight": 1.5},
        "hdng": {"name": "Heading", "importance_weight": 1.5},
        "flwr": {"name": "Flowering", "importance_weight": 1.6},
        "grnm": {"name": "Grain Filling", "importance_weight": 1.6},
        "rpng": {"name": "Ripening", "importance_weight": 0.9},
        "hrvst": {"name": "Harvest", "importance_weight": 0.8}
    }
    
    stages_list = []
    pred_data = results_df.iloc[0]
    
    for stage_code, stage_details in stage_map.items():
        stage_entry = {
            "name": stage_details["name"],
            "duration_days": int(round(pred_data.get(f'{stage_code}_stage_dur', 0))),
            "importance_weight": stage_details["importance_weight"],
            "ideal": {
                "tmin_c": round(pred_data.get(f'{stage_code}_tmin', 0.0), 2),
                "tmax_c": round(pred_data.get(f'{stage_code}_tmax', 0.0), 2),
                "rh_pct": int(round(pred_data.get(f'{stage_code}_rh', 0))),
                "rain_mm": round(pred_data.get(f'{stage_code}_rain', 0.0), 2),
                "wind_kmph": round(pred_data.get(f'{stage_code}_wind', 0.0), 2),
            },
            "forecasted": {}
        }
        stages_list.append(stage_entry)
        
    final_json = {
        "state": input_data['state'].iloc[0] if 'state' in input_data.columns else None,
        "total_duration_days": int(round(results_df['total_duration_estimate'].iloc[0])),
        "meta": {
            "version": "1.0",
            "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "notes": "Ideal stage-level dataset generated by the prediction model."
        },
        "crop": input_data['crop'].iloc[0],
        "sw_date": input_data['sw_date'].iloc[0] if 'sw_date' in input_data.columns else None,
        "district": input_data['district'].iloc[0],
        "stages": stages_list
    }
    
    return final_json

@app.route("/predict", methods=['POST'])
def predict():
    if model_pipeline is None:
        return jsonify({"error": "Model is not loaded. Please check server logs."}), 500
        
    try:
        json_data = request.get_json()
        if not json_data:
            return jsonify({"error": "No input data provided"}), 400
            
        input_data = pd.DataFrame(json_data, index=[0])
        raw_prediction = model_pipeline.predict(input_data)
        
        formatted_response = format_prediction_to_detailed_json(raw_prediction, input_data)
        
        return jsonify(formatted_response)
    
    except Exception as e:
        print(traceback.format_exc())
        return jsonify({"error": f"An error occurred during prediction: {str(e)}"}), 500

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000, debug=True)